export const LOADING = 'LOADING';
export const ERROR = 'ERROR';

export const GET_TASK_SUCCESS = 'GET_TASK_SUCCESS';

export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';

export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';
export const ADDING_TASK = 'ADDING_TASK';

export const REMOVING_TASK = 'REMOVING_TASK';
export const REMOVE_TASK_SUCCESS = 'REMOVE_TASK_SUCCESS';

export const REMOVING_TASKS = 'REMOVING_TASKS';
export const REMOVE_TASKS_SUCCESS = 'REMOVE_TASKS_SUCCESS';

export const EDITING_TASK = 'EDITING_TASK';
export const EDIT_TASK_SUCCESS = 'EDIT_TASK_SUCCESS';
<<<<<<< HEAD

export const CHANGING_TASK_STATUS = 'CHANGING_TASK_STATUS';
export const CHANGE_TASK_STATUS_SUCCESS = 'CHANGE_TASK_STATUS_SUCCESS';
=======
>>>>>>> fd64dd4617e0d05c99a64df782d3d762d41ed850
